version: '3.8'

services:
  web:
    build: .
    container_name: php-bookstore
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - db_data:/var/lib/mysql
      - ./database/bookstore.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
